#!/usr/bin/env node
/* Vendors the Phosphor Regular glyphs this site draws, straight from the Phosphor core repo.
 *
 *   npm run icons
 *
 * From the SOURCE, never out of another product's tree. A copy of a copy has no source left to
 * re-read, and there is no shared component library to take one from: those repos were purged on
 * 2026-09-14 and every app in the estate vendors its own set.
 *
 * The glyphs compile into src/lib/phosphor.ts as path bodies in currentColor, so a glyph takes
 * the ink of whatever sits beside it. No icon font, no runtime CDN, no colour of its own.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'vendor/phosphor');
const BASE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/assets/regular';
const LICENSE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/LICENSE';

/* ONE GLYPH PER CALLER. Seven of them are the seven rules, one each, and the glyph says what that
 * rule reads off the page rather than decorating it. A glyph with no caller is a glyph to delete,
 * so this list and src/lib/product.ts are checked against each other by scripts/check-register.mjs. */
const WANT = [
  'circle-half', // contrast: two tones against each other
  'columns', // dead-column: the width the page leaves unused
  'browser', // page-chrome: the nav and footer a route lost
  'image', // figure: a picture at the full measure
  'hash', // stat-eyebrow: a numeral set as the subject
  'table', // table-shape: a grid a reader scans two ways
  'quotes', // noise: the page's own copy
  'terminal-window', // the console, and the captured output
  'list-checks', // the rules route
  'download-simple', // the install route
  'github-logo', // the source
  'package', // the published package
  'caret-up-down', // the app switch beside the mark
  'caret-right', // a row that opens
  'clipboard-text', // copy the install line
  'check', // exit 0, checked and clean
  'x', // exit 1, checked and violating
  'warning-circle', // exit 2, could not check
  'prohibit', // the three things this package does not have
  'ruler', // a measured threshold
  'lightning', // the run line
  'clock', // a read date
  'info', // a note in a rail
  'arrow-square-out', // an outward link
];

await mkdir(OUT, { recursive: true });
const index = {};
for (const name of WANT) {
  const url = `${BASE}/${name}.svg`;
  const r = await fetch(url);
  if (!r.ok) throw new Error(`HTTP ${r.status} on ${url}`);
  const svg = await r.text();
  const body = svg
    .replace(/<\?xml[\s\S]*?\?>/g, '')
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/fill="#[0-9a-fA-F]{3,8}"/g, 'fill="currentColor"')
    .trim();
  await writeFile(resolve(OUT, `${name}.svg`), svg);
  index[name] = body;
  process.stdout.write(`${name}  ${svg.length}b\n`);
}
const lic = await fetch(LICENSE);
if (!lic.ok) throw new Error(`HTTP ${lic.status} on the licence`);
await writeFile(resolve(OUT, 'LICENSE'), await lic.text());

await writeFile(
  resolve(ROOT, 'src/lib/phosphor.ts'),
  `// GENERATED by scripts/icons.mjs from ${BASE}\n` +
    `// Phosphor Icons, MIT. The licence is vendored at vendor/phosphor/LICENSE.\n` +
    `export const GLYPH: Record<string, string> = ${JSON.stringify(index, null, 1)};\n` +
    `export type GlyphName = keyof typeof GLYPH;\n`,
);
process.stdout.write(`\nwrote src/lib/phosphor.ts, ${WANT.length} glyphs\n`);
